---
title: "KOGPSY"
description: |
  Welcome to the website for *Kognitionspsychologie I* HS24 ([23263-01](https://vorlesungsverzeichnis.unibas.ch/de/home?id=284655))
  
  Instructor: [Rui Mata](https://psychologie.unibas.ch/de/personen/rui-mata/about-me/), University of Basel
  
  **Last updated:** `r format(Sys.time(), "%a %b %d %X %Y")`
  
site: distill::distill_website
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

# Learn more about creating websites with Distill at:
# https://rstudio.github.io/distill/website.html

# Learn more about publishing to GitHub Pages at:
# https://rstudio.github.io/distill/publish_website.html#github-pages

```

![Thinking is simply using one's brain! <span>Photo by <a href="https://unsplash.com/@jessemartini?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Jesse Martini</a> on <a href="https://unsplash.com/s/photos/brain?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>](photos/jesse-martini-Iod3vdjKE1E-unsplash.jpg)

# Session information

Sessions take place Tuesdays, 10.15-11.45, Pharmazentrum, Hörsaal 1. 

::: l-body
| # | Date     | Topic                         | Slides |
|---| ---------|-------------------------------|--------|
| 1 | 01.10.2024 | Session 1: Introduction | tba |
| 2 | 08.10.2024 | Session 2: Intelligence | tba |
| 3 | 15.10.2024 | Session 3: Visual perception | tba |
| 4 | 22.10.2024 | Session 4: Spatial cognition | tba |
| 5 | 29.10.2024 | Session 5: Numerical cognition | tba |
| 6 | 05.11.2024 | Session 6: Language | tba |
| 7 | 12.11.2024 | Session 7: Knowing | tba |
| 8 | 19.11.2024 | Session 8: Consciousness | tba |
| 9 | 26.11.2024 | Session 9: Applications | tba |
|10 | 03.12.2024 | Session 10: Applications | tba |
|11 | 10.12.2024 | Session 11: Applications | tba |
|12 | 17.12.2024 | Session 12: Wrap-up and Q&A | tba |
:::

# What is this course about?

This course aims to give a broad introduction to central topics in psychology, with a focus on mechanistic and pluralistic explanations of cognition. 

# What can you expect to learn?

By completing the course you can expect to...

- reflect about the need for mechanistic and pluralistic explanations in psychology
- learn about central theories and models in key areas of psychology
- become familiarized with common methods used in psychology
- learn about examples of applications of psychology to real-world contexts

# How should you use this website?

This website is designed to help course participants get an overview of the course and the course slides (which will be made available either shortly after or before each session). A [FAQ](https://adam.unibas.ch/goto_adam_crs_1736790.html) forum is available on ADAM. 